[project]
name = "konsulent-api"
version = "0.1.0"
description = "API som eksponerer konsulentdata"
dependencies = [
    "fastapi",
    "uvicorn",
    "pytest",
    "httpx"
]

[tool.pytest.ini_options]
testpaths = ["tests"]