services:
  konsulent-api:
    build: ./konsulent-api
    container_name: konsulent-api
    ports:
      - "8001:8000"

  llm-verktoy-api:
    build: ./llm-verktoy-api
    container_name: llm-verktoy-api
    ports:
      - "8002:8000"
    depends_on:
      - konsulent-api
    env_file:
      - .env  
